### Reading Data from different Sources

When working with data, it's important to know how to read data from various sources. Here are some common methods for reading data:
1. **Reading from CSV Files**: 
   - You can use libraries like `pandas` in Python to read CSV files easily.
   ```python
   import pandas as pd
   data = pd.read_csv('data.csv')
   ```
2. **Reading from Excel Files**:
    - The `pandas` library also provides functionality to read Excel files.
    ```python
    data = pd.read_excel('data.xlsx')
    ```
3. **Reading from SQL Databases**:
    - You can use libraries like `SQLAlchemy` or `sqlite3` to connect to SQL databases and read data.
    ```python
    import sqlite3
    conn = sqlite3.connect('database.db')
    data = pd.read_sql_query('SELECT * FROM table_name', conn)
    ```
4. **Reading from JSON Files**:
    - JSON files can be read using the `json` library or `pandas`.
    ```python
    import json
    with open('data.json') as f:
        data = json.load(f)
    ```
    - Alternatively, using `pandas`:
    ```python
    data = pd.read_json('data.json')
    ```
5. **Reading from APIs**:
    - You can use the `requests` library to fetch data from APIs.
    ```python
    import requests
    response = requests.get('https://api.example.com/data')
    data = response.json()
    ```
With all these methods, you can easily read data from different sources and start analyzing it. Make sure to handle exceptions and errors appropriately when reading data to ensure your program runs smoothly.

In [6]:
import pandas as pd
from io import StringIO

data = '{"name":"Mamun", "Class":"B.E 3rd", "Address":[{"city":"chandigarh", "country":"India"}]}'
df=pd.read_json(StringIO(data))
print(df)

    name    Class                                     Address
0  Mamun  B.E 3rd  {'city': 'chandigarh', 'country': 'India'}

In [ ]:
df.to_json()
# df.to_json(orient='index') which is the default orientation

'{"name":{"0":"Mamun"},"Class":{"0":"B.E 3rd"},"Address":{"0":{"city":"chandigarh","country":"India"}}}'

In [8]:
df.to_json(orient='records')  # to get a list of records

'[{"name":"Mamun","Class":"B.E 3rd","Address":{"city":"chandigarh","country":"India"}}]'

In [10]:
pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   --------------- ------------------------ 1.6/4.1 MB 5.8 MB/s eta 0:00:01
   ------------------------------ --------- 3.1/4.1 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 6.5 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
url = "https://afd.calpoly.edu/web/sample-tables"

df=pd.read_html(url)  # returns a list of dataframes
df[0]  # first table
# df=pd.read_html(url, match='Date', header=0)  # first row as header

,Description,Date,Location
0,Academic Senate Meeting,"May 25, 2205",Building 99 Room 1
1,Commencement Meeting,"December 15, 2205",Building 42 Room 10
2,Dean's Council,"February 1, 2206",Building 35 Room 5
3,Committee on Committees,"March 3, 2206",Building 1 Room 201
4,"Lorem ipsum dolor sit amet, consectetuer adipi...","Lorem ipsum dolor sit amet, consectetuer adipi...","Lorem ipsum dolor sit amet, consectetuer adipi..."
5,Lorem ipsum dolor,Lorem ipsum dolor,Lorem ipsum dolor

In [14]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [21]:
df_excel = pd.read_excel('excel_data.xlsx')
df_excel.to_pickle('df_excel.pkl')
pd.read_pickle('df_excel.pkl')

,Unnamed: 0,Table,1. State & Type - Wise Number of Universities,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Sl. No.,State,Central University,Central Open University,Institute of National Importance,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total,NaN,Govt.,Govt. Aided,Private
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,NaN,NaN,NaN,NaN
2,1,Andhra Pradesh,2,0,10,23,1,0,5,0,0,0,4,45,NaN,NaN,NaN,NaN
3,2,Arunachal Pradesh,1,0,1,0,0,0,6,1,1,0,0,10,NaN,NaN,NaN,NaN
4,3,Assam,2,0,5,13,0,1,6,0,1,0,0,28,NaN,NaN,NaN,NaN
5,4,Bihar,4,0,6,17,1,1,7,0,1,0,0,37,NaN,NaN,NaN,NaN
6,5,Chandigarh,0,0,1,1,0,0,0,0,1,0,0,3,NaN,NaN,NaN,NaN
7,6,Chhattisgarh,1,0,4,14,0,1,12,0,0,0,0,32,NaN,NaN,NaN,NaN
8,7,Delhi,6,1,5,8,0,0,0,0,6,1,1,28,NaN,NaN,NaN,NaN
9,8,Goa,0,0,2,1,0,0,0,0,0,0,0,3,NaN,NaN,NaN,NaN
10,9,Gujarat,1,0,9,25,0,1,44,0,1,1,1,83,NaN,NaN,NaN,NaN
11,10,Haryana,1,0,5,20,0,0,24,0,3,0,3,56,NaN,NaN,NaN,NaN
12,11,Himachal Pradesh,1,0,4,7,0,0,17,0,0,0,0,29,NaN,NaN,NaN,NaN
13,12,Jammu and Kashmir,2,0,3,9,1,0,0,0,0,0,0,15,NaN,NaN,NaN,NaN
14,13,Jharkhand,1,0,5,11,0,0,14,0,0,0,1,32,NaN,NaN,NaN,NaN
15,14,Karnataka,1,0,6,32,0,1,18,0,3,0,11,72,NaN,NaN,NaN,NaN
16,15,Kerala,1,0,6,13,0,0,0,0,2,0,1,23,NaN,NaN,NaN,NaN
17,16,Ladakh,0,0,0,1,0,0,0,0,1,0,0,2,NaN,NaN,NaN,NaN
18,17,Madhya Pradesh,2,0,9,22,0,1,39,0,1,0,0,74,NaN,NaN,NaN,NaN
19,18,Maharashtra,1,0,7,23,0,1,18,0,7,2,12,71,NaN,NaN,NaN,NaN
20,19,Manipur,3,0,2,3,0,0,1,0,0,0,0,9,NaN,NaN,NaN,NaN
21,20,Meghalaya,1,0,2,0,0,0,8,0,0,0,0,11,NaN,NaN,NaN,NaN
22,21,Mizoram,1,0,1,0,0,0,1,0,0,0,0,3,NaN,NaN,NaN,NaN
23,22,Nagaland,1,0,1,0,0,0,3,0,0,0,0,5,NaN,NaN,NaN,NaN
24,23,Odisha,1,0,5,18,0,1,8,0,0,0,3,36,NaN,NaN,NaN,NaN
25,24,Puducherry,1,0,2,0,0,0,0,0,0,0,1,4,NaN,NaN,NaN,NaN
26,25,Punjab,1,0,6,10,0,0,15,0,1,0,1,34,NaN,NaN,NaN,NaN
27,26,Rajasthan,1,0,5,26,0,1,52,0,0,0,7,92,NaN,NaN,NaN,NaN
28,27,Sikkim,1,0,1,1,0,0,5,0,0,0,0,8,NaN,NaN,NaN,NaN
29,28,Tamil Nadu,2,0,7,21,0,1,0,0,0,2,26,59,NaN,NaN,NaN,NaN
30,29,Telangana,3,0,4,15,1,1,4,0,1,0,2,31,NaN,NaN,NaN,NaN
31,30,Tripura,1,0,2,1,0,0,1,0,0,0,0,5,NaN,NaN,NaN,NaN
32,31,Uttar Pradesh,5,0,11,28,1,1,29,0,2,3,4,84,NaN,NaN,NaN,NaN
33,32,Uttarakhand,1,0,4,11,0,1,17,0,1,1,1,37,NaN,NaN,NaN,NaN
34,33,West Bengal,1,0,8,29,0,1,11,0,1,0,1,52,NaN,NaN,NaN,NaN
35,All India,NaN,51,1,149,403,5,14,365,1,34,10,80,1113,NaN,446,NaN,NaN
36,NaN,"In UTs of , Andaman & Nicobar Islands, Dadra ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,Government,657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,Private,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,Government Aided,446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Other than these, you can also read data from HTML tables, XML files, and more. The `pandas` library provides a wide range of functions to read data from various formats, making it a powerful tool for data analysis.